# Generated by Django 2.0.6 on 2019-03-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetail',
            old_name='invoice',
            new_name='logo',
        ),
    ]
