# Generated by Django 2.0.6 on 2019-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190327_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedetail',
            name='msg',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
