# Generated by Django 2.0.6 on 2019-03-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_messagedetail_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(default=0)),
                ('msg', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.CompanyDetail')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parentmessage',
            unique_together={('company', 'parent')},
        ),
    ]
