# Generated by Django 2.0.6 on 2019-03-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190328_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedetail',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='messagedetail',
            name='type',
        ),
    ]
